version: "3.8"
services:
  dev-mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: udemy
      MYSQL_DATABASE: udemy
      MYSQL_USER: udemy
      MYSQL_PASSWORD: udemy
    restart: always
    networks:
      - lesson
networks:
  lesson: